main: Plugin
name: FunPlugin
version: 1.0
api-version: "1.20"
author: Groovin-Dev
description: A fun testing plugin
commands:
  givegrapple:
    description: Gives the player a grapple
    usage: /givegrapple
